version: "3"

services:
  faucet:
    image: voidxnull/zeropool-faucet:latest
    ports:
      - "80:80"
    environment:
      - PORT=80
      - INTERVAL=86400000 # 24 hours
      - NEAR_RPC_URL=https://rpc.testnet.near.org
      - NEAR_ACCOUNT_ID=
      - NEAR_SECRET_KEY=
      - NEAR_AMOUNT=5000000000000000000000000 # 5 NEAR
