#!/usr/bin/env bash

PARENT_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )/.." &> /dev/null && pwd )"

USERNAME=voidxnull
IMAGE=zeropool-faucet
VERSION=$(grep version "$PARENT_DIR"/Cargo.toml | head -n1 | sed -E 's/.*version = "(.*)"/\1/')

echo "$USERNAME/$IMAGE:latest"
echo "$USERNAME/$IMAGE:$VERSION"

docker build -f ./Dockerfile -t $USERNAME/$IMAGE:latest . && \
docker tag $USERNAME/$IMAGE:latest $USERNAME/$IMAGE:$VERSION && \
docker push $USERNAME/$IMAGE:latest && \
docker push $USERNAME/$IMAGE:$VERSION